### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character u'\u258f' in position 87: ordinal not in range(128)

### ISSUE THREAD

**Issue by 91koff** [ndbroadbent/icloud_photos_downloader#70]
Looking up all photos...
Downloading 11051 original photos and videos to /mnt/path/ ...
/mnt/path/2018/04/16/IMG_6667-original.HEIC already exists.:   0%|                                                                                                                                                 | 1/11051 [00:03<11:01:05,  3.59s/it]Traceback (most recent call last):
  File "./download_photos.py", line 304, in <module>
    download()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "./download_photos.py", line 142, in download
    for photo in progress_bar:
  File "/usr/local/lib/python2.7/dist-packages/tqdm/_tqdm.py", line 607, in __iter__
    1 / avg_time if avg_time else None, bar_format))
  File "/usr/local/lib/python2.7/dist-packages/tqdm/_tqdm.py", line 98, in print_status
    fp_write('\r' + s + (' ' * max(last_printed_len[0] - len_s, 0)))
  File "/usr/local/lib/python2.7/dist-packages/tqdm/_tqdm.py", line 92, in fp_write
    fp.write(_unicode(s))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u258f' in position 87: ordinal not in range(128)

**Comment by bexelbie** [comment]
I tried briefly to reproduce this.  I could not.  Can you produce the unicode character 258f at your command prompt?

**Comment by 91koff** [comment]
Like this?
printf u'\u258e'
u▎

**Comment by bexelbie** [comment]
yep.  My only guess was you had a font or something similar that didn't support unicode or that character.  I'm not able to repro this bug with my data set.

**Comment by morhook** [comment]
I'm getting same error on my run. If it helps:
```
./download_photos.py ~/Imágenes/backup_icloud --username=$MY_ICLOUD_USER --auto-delete 
No handlers could be found for logger "keyring.backend"
Looking up all photos...
Downloading 885 original photos to /home/cruzyfer/Imágenes/backup_icloud/ ...
/home/cruzyfer/Imágenes/backup_icloud/2018/04/10/camphoto_1483920592-original.jpg already exists.:   0%| | 1/885 [00:02<43:55,  2.98s/it]Traceback (most recent call last):
  File "./download_photos.py", line 304, in <module>
    download()
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "./download_photos.py", line 142, in download
    for photo in progress_bar:
  File "/home/cruzyfer/.local/lib/python2.7/site-packages/tqdm/_tqdm.py", line 607, in __iter__
    1 / avg_time if avg_time else None, bar_format))
  File "/home/cruzyfer/.local/lib/python2.7/site-packages/tqdm/_tqdm.py", line 227, in format_meter
    return l_bar + full_bar + r_bar
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 29: ordinal not in range(128)
```

**Comment by bexelbie** [comment]
@91koff I was thinking the terminal, but your print seemed to work too.  I am not familiar enough with the code base to suggest anything else.  However, I wonder if you and @morhook are using the same operating system and package source.  That might pin it down some.

**Comment by 91koff** [comment]
OK, I've got the answer.

My u'\u258f' symbol is a symbol that is used to draw a "progress bar" in a line like this (look at the end of line just after 0%):

```
Downloading /mnt/data/photo/icloudfiles/yakov/2018/05/06/IMG_7053-original.HEIC:   0%|▏
```

How I fixed it.

```
$ locale
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=en_US.UTF-8
LANGUAGE=en_US:en
LC_CTYPE=UTF-8
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
$ sudo update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8
$ sudo reboot
```

Check if LC_ALL is set.

```
$ locale
LANG=en_US.UTF-8
LANGUAGE=en_US:en
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8
```

Try one more time

```
./download_photos.py --username XXX --password XXX --download-videos /mnt/data/photo/icloudfiles/91koff
Two-step/two-factor authentication is required.
  0: SMS to **********
  1: Enter two-factor authentication code
Please choose an option: [0]: 1
Please enter two-factor authentication code: 123456
Great, you're all set up. The script can now be run without user interaction.
You can also set up email notifications for when the two-step authentication expires.
(Use --help to view information about SMTP options.)
Looking up all photos...
Downloading 11421 original photos and videos to /mnt/data/photo/icloudfiles/91koff/ ...
Downloading /mnt/data/photo/icloudfiles/91koff/2018/05/06/IMG_7053-original.HEIC:   0%|▏                                                                                                                                                    | 14/11421 [00:10<5:42:06,  1.80s/it]
Downloading /mnt/data/photo/icloudfiles/91koff/2018/05/06/IMG_7048-original.MOV:   0%|▏                                                                                                                                                   | 19/11421 [06:35<155:37:53, 49.14s/it]
```

@bexelbie probably you can add a kind of a precheck to a download script which confirms that LC_ALL is set and if not, asks to set it.

**Comment by nicojx** [comment]
I have LC_ALL set to en_US.UTF-8, but the error still occurs when running the script as cron job. According to here: http://www.logikdev.com/2010/02/02/locale-settings-for-your-cron-job/, the trick to create (if not already present) the file _/etc/environment_ and add the following line: 
`LANG=en_US.UTF-8.` 

The cron process will read this file when it starts, so you need to restart it in order to apply the change:
`service cron restart`

**Comment by cdangerdouglas** [comment]
I am having the same issue on windows 10. this is not a solution but it is a work around for windows users:
2. download/install VirtualBox
3. dowload a linux iso (i used lubuntu)
4. create a linux virtual machine, install python and icloud_photos_downloader
5. run icloud_photos_downloader

**Comment by sthenge** [comment]
I'm experiencing this also, however, it only seems to happen when I am redirecting the stdout/stderr to a file.

This is my cron_script.sh script:

#!/bin/bash
# Make sure we are in the right directory
mypath=`realpath $0`
cd ~/icloud_photos_downloader
echo "$(date) Icloud Photo Update" >>/home/bill/Log/icloud.log
# Make sure only one instance is running
pgrep -f download_photos.py && echo "download_photos.py is already running." ||
  /usr/bin/env python download_photos.py /home/bill/Pictures/Icloud \
	--username=myaccount\
	--password=mypassword \
	--auto-delete \
	--download-videos \
	&>>/home/bill/Log/icloud.log
echo "$(date) Update Finished" >>/home/bill/Log/icloud.log

It fails as explained above whether executed by cron or manually in a terminal.  When I comment out the "&>>/home/bill/Log/icloud.log" the script works, at least from the terminal. Not sure from cron because there is no output.

My local photo directories are up to date so the failure occurs while doing the "file exist" lookup.
Here is the error report:

File "./download_photos.py", line 304, in <module>
    download()
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "./download_photos.py", line 142, in download
    for photo in progress_bar:
  File "/usr/local/lib/python2.7/dist-packages/tqdm/_tqdm.py", line 607, in __iter__
    1 / avg_time if avg_time else None, bar_format))
  File "/usr/local/lib/python2.7/dist-packages/tqdm/_tqdm.py", line 98, in print_status
    fp_write('\r' + s + (' ' * max(last_printed_len[0] - len_s, 0)))
  File "/usr/local/lib/python2.7/dist-packages/tqdm/_tqdm.py", line 92, in fp_write
    fp.write(_unicode(s))
  File "/usr/lib/python2.7/dist-packages/colorama/ansitowin32.py", line 40, in write
    self.__convertor.write(text)
  File "/usr/lib/python2.7/dist-packages/colorama/ansitowin32.py", line 141, in write
    self.write_and_convert(text)
  File "/usr/lib/python2.7/dist-packages/colorama/ansitowin32.py", line 169, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "/usr/lib/python2.7/dist-packages/colorama/ansitowin32.py", line 174, in write_plain_text
    self.wrapped.write(text[start:end])
UnicodeEncodeError: 'ascii' codec can't encode character u'\u258f' in position 85: ordinal not in range(128)

**Comment by ndbroadbent** [comment]
Sorry about the delay, and thanks for the tip about `LC_ALL`! It sounds like this is coming from the `tqdm` library, and might be related to: https://github.com/tqdm/tqdm/issues/365

`tqdm` has the `ascii` option, so I've just set that to `True`: https://github.com/ndbroadbent/icloud_photos_downloader/commit/7f304ea99d24f6bddbc14093739bb18d449ee613

Hopefully that will reduce the unicode errors and fix cron scripts. Closing for now, but please let me know if you are still experiencing unicode errors related to the `tqdm` progress bar.

Also another note, but I should probably change the output for cron scripts. If there's no tty then it should probably output regular log messages with timestamps. Not sure if I have time for that, but PRs welcome if that would be useful to anyone!
